### ISSUE TITLE
[BUG] Segmentation Fault while building disk index

### ISSUE THREAD

**Issue by rodrigonascimento** [microsoft/DiskANN#472]
## Expected Behavior
Trying to build the indexes for the 1B BigANN dataset.

## Actual Behavior
Running the /root/DiskANN/build/apps/build_disk_index fails with a segmentation fault.

## Example Code
Please see [How to create a Minimal, Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for some guidance on creating the best possible example of the problem
```bash
/root/DiskANN/build/apps/build_disk_index --data_type float --dist_fn l2 --data_path bigann_base.fbin --index_path_prefix index_bigann_1b_R64_L100 -R 64 -L 100 -B 0.003 -M 128
```

## Dataset Description
Please tell us about the shape and datatype of your data, (e.g. 128 dimensions, 12.3 billion points, floats)
- Dimensions: 128
- Number of Points: 1B
- Data type: float

## Error 

Here is a run using GDB and a backtrace:

```
Reading symbols from /root/DiskANN/build/apps/build_disk_index...
(gdb)
(gdb) run --data_type float --dist_fn l2 --data_path bigann_base.fbin --index_path_prefix index_bigann_1b_R64_L100 -R 64 -L 100 -B 0.003 -M 128
Starting program: /root/DiskANN/build/apps/build_disk_index --data_type float --dist_fn l2 --data_path bigann_base.fbin --index_path_prefix index_bigann_1b_R64_L100 -R 64 -L 100 -B 0.003 -M 128
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Starting index build: R=64 L=100 Query RAM budget: 3.22123e+06 Indexing ram budget: 128 T: 40
Compressing 128-dimensional data into 1 bytes per vector.
Opened: bigann_base.fbin, size: 130976743944, cache_size: 67108864
Training data with 256522 samples loaded.
Processing chunk 0 with dimensions [0, 128)
[New Thread 0x7fffeddfa6c0 (LWP 6095)]
[New Thread 0x7fffed5f8740 (LWP 6096)]
[New Thread 0x7fffecdf67c0 (LWP 6097)]
[New Thread 0x7fffec5f4840 (LWP 6098)]
[New Thread 0x7fffebdf28c0 (LWP 6099)]
[New Thread 0x7fffeb5f0940 (LWP 6100)]
[New Thread 0x7fffeadee9c0 (LWP 6101)]
[New Thread 0x7fffea5eca40 (LWP 6102)]
[New Thread 0x7fffe9deaac0 (LWP 6103)]
[New Thread 0x7fffe95e8b40 (LWP 6104)]
[New Thread 0x7fffe8de6bc0 (LWP 6105)]
[New Thread 0x7fffe85e4c40 (LWP 6106)]
[New Thread 0x7fffe7de2cc0 (LWP 6107)]
[New Thread 0x7fffe75e0d40 (LWP 6108)]
[New Thread 0x7fffe6ddedc0 (LWP 6109)]
[New Thread 0x7fffe65dce40 (LWP 6110)]
[New Thread 0x7fffe5ddaec0 (LWP 6111)]
[New Thread 0x7fffe55d8f40 (LWP 6112)]
[New Thread 0x7fffe4dd6fc0 (LWP 6113)]
[New Thread 0x7fffe45d5040 (LWP 6114)]
[New Thread 0x7fffe3dd30c0 (LWP 6115)]
[New Thread 0x7fffe35d1140 (LWP 6116)]
[New Thread 0x7fffe2dcf1c0 (LWP 6117)]
[New Thread 0x7fffe25cd240 (LWP 6118)]
[New Thread 0x7fffe1dcb2c0 (LWP 6119)]
[New Thread 0x7fffe15c9340 (LWP 6120)]
[New Thread 0x7fffe0dc73c0 (LWP 6121)]
[New Thread 0x7fffe05c5440 (LWP 6122)]
[New Thread 0x7fffdfdc34c0 (LWP 6123)]
[New Thread 0x7fffdf5c1540 (LWP 6124)]
[New Thread 0x7fffdedbf5c0 (LWP 6125)]
[New Thread 0x7fffde5bd640 (LWP 6126)]
[New Thread 0x7fffdddba6c0 (LWP 6127)]
[New Thread 0x7fffdd5b7740 (LWP 6128)]
[New Thread 0x7fffdcdb47c0 (LWP 6129)]
[New Thread 0x7fffdc5b1840 (LWP 6130)]
[New Thread 0x7fffdbdae8c0 (LWP 6131)]
[New Thread 0x7fffdb5ab940 (LWP 6132)]
[New Thread 0x7fffdada89c0 (LWP 6133)]

Thread 7 "build_disk_inde" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb5f0940 (LWP 6100)]
0x000000000087d5f9 in math_utils::compute_closest_centers(float*, unsigned long, unsigned long, float*, unsigned long, unsigned long, unsigned int*, std::vector<unsigned long, std::allocator<unsigned long> >*, float*) [clone ._omp_fn.0] ()
Missing separate debuginfos, use: dnf debuginfo-install intel-oneapi-openmp-2023.2.0-2023.2.0-49495.x86_64
(gdb) bt
#0  0x000000000087d5f9 in math_utils::compute_closest_centers(float*, unsigned long, unsigned long, float*, unsigned long, unsigned long, unsigned int*, std::vector<unsigned long, std::allocator<unsigned long> >*, float*) [clone ._omp_fn.0] ()
#1  0x00007fffeecb60ec in __kmp_GOMP_microtask_wrapper () from /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so
#2  0x00007fffeed63493 in __kmp_invoke_microtask () from /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so
#3  0x00007fffeecd1533 in __kmp_invoke_task_func () from /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so
#4  0x00007fffeecd0470 in __kmp_launch_thread () from /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so
#5  0x00007fffeed641ff in _INTERNAL1ebb3278::__kmp_launch_worker(void*) () from /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin/libiomp5.so
#6  0x00007fffee29f802 in start_thread (arg=<optimized out>) at pthread_create.c:443
#7  0x00007fffee23f450 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

## Your Environment
* RedHat Enterprise Linux 9.2; Kernel: 5.14.0-284.11.1.el9_2.x86_64
* DiskANN version Commit: a5334dd89ee0cf305e8757ed1bb373258537d2d9

## Additional Details
Steps followed to configure the environment to build DiskANN
```
## install required packages
yum install make cmake libaio-devel clang clang-devel git-clang-format python3-clang boost-devel autoconf automake libtool
 
### install Google Performance Tools (TCMALLOC) for RHEL 8.8
git clone https://github.com/gperftools/gperftools.git
cd gperftools
./autogen.sh
./configure
make
make check
make install
 
### create Intel's ONE API repo file
tee > /etc/yum.repos.d/oneAPI.repo << EOF
[oneAPI]
name=Intel® oneAPI repository
baseurl=https://yum.repos.intel.com/oneapi
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
EOF
 
### install Intel-Optimized Math Library for Numerical Computing on CPUs & GPUs
yum install -y intel-oneapi-mkl intel-oneapi-mkl-devel-2023.2.0 
 
### building DiskANN
mkdir DiskANN/build && cd DiskANN/build && cmake -DCMAKE_BUILD_TYPE=Release -DMKL_INCLUDE_PATH=/opt/intel/oneapi/mkl/2023.2.0 .. && make -j
```

**Comment by harsha-simhadri** [comment]
You choose B=0.003, that is 3MB to host PQ data over a billion points in memory. That is impossible to support since it leaves fewer than 1 bit per vector.    Please try with B=32 or a similar value. 
 
 Also, feel free to submit a PR that forces the code to fail earlier with small B values.
